baseURL = "https://dceoy.github.io/aims/"
locale = "en-us"
defaultContentLanguage = "en"
title = "AIMS"
publishDir = "site"
disableKinds = ["taxonomy", "term"]
enableRobotsTXT = true
summaryLength = 0

[pagination]
  pagerSize = 15

[outputs]
  home = ["HTML", "RSS", "JSON"]
